/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "clc.h"

void *
inicializa_random_1_svc(int arg1,  struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */
	printf("Se llamó a inicializa_random_1_svc");
	srandom(arg1);
	return (void *) &result;
}

int *
obtiene_1er_random_1_svc(struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	result = random() % 50;
	printf("se llamo a obtiene_1er_random_1_svc");
	return &result;
}

int *
obtiene_2do_random_1_svc(struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	result = random() % 50;
	printf("se llamo a obtiene_2do_random_1_svc");
	return &result;
}

int *
suma_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	result = arg1 + arg2;
	printf("se llamo a suma_1_svc");
	return &result;
}

int *
resta_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	result = arg1 - arg2;
	printf("se llamo a resta_1_svc");
	return &result;
}

int *
multiplicacion_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	result = arg1 * arg2;
	printf("se llamo a multiplicacion_1_svc");
	return &result;
}

int *
division_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	 printf("se llamo a division_1_svc");
	result = arg1 / arg2;
	
	return &result;
}
