/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "clc.h"


void
clc_prog_1(char *host, int semilla)
{
	CLIENT *clnt;
	void  *result_1;
	int inicializa_random_1_arg1;
	int  *result_2;
	int  *result_3;
	int  *result_4;
	int suma_1_arg1;
	int suma_1_arg2;
	int  *result_5;
	int resta_1_arg1;
	int resta_1_arg2;
	int  *result_6;
	int multiplicacion_1_arg1;
	int multiplicacion_1_arg2;
	int  *result_7;
	int division_1_arg1;
	int division_1_arg2;
	
	inicializa_random_1_arg1 = semilla;

#ifndef	DEBUG
	clnt = clnt_create (host, CLC_PROG, CLC_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = inicializa_random_1(inicializa_random_1_arg1, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else {
		printf("¡Inicializado de forma exitosa!");
	}
	
	result_2 = obtiene_1er_random_1(clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else {
		printf("\nAleatorio 1: %d", *result_2);
	}
	
	result_3 = obtiene_2do_random_1(clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else {
		printf("\nAleatorio 2: %d", *result_3);
	}
	
	suma_1_arg1 = *result_2;
	suma_1_arg2 = *result_3;
	
	result_4 = suma_1(suma_1_arg1, suma_1_arg2, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else {
		printf("\nSuma: %d", *result_4);
	}

	resta_1_arg1 = *result_2;
	resta_1_arg2 = *result_3;
	
	result_5 = resta_1(resta_1_arg1, resta_1_arg2, clnt);
	if (result_5 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else {
		printf("\nResta: %d", *result_5);
	}
	
	multiplicacion_1_arg1 = *result_2;
	multiplicacion_1_arg2 = *result_3;
	
	result_6 = multiplicacion_1(multiplicacion_1_arg1, multiplicacion_1_arg2, clnt);
	if (result_6 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else {
		printf("\nMultiplicación: %d", *result_6);
	}
	
	division_1_arg1 = *result_2;
	division_1_arg2 = *result_3;
	
	result_7 = division_1(division_1_arg1, division_1_arg2, clnt);
	if (result_7 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else {
		printf("\nDivisión: %d\n", *result_7);
	}
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int semilla;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	clc_prog_1 (host, semilla);
exit (0);
}
